const express = require('express')
const router = express.Router()
const {getRides,editRide,cancelRide,getRide,newRide,getBookings,addBookings} = require('../controllers/rides')
const {getUser,saveUser} = require('../controllers/user')
const authorize =  require('../middleware/authorize')

router.use(authorize)
router.route('/ev')
    .get()
    .post()
router.route('/ride')
    .get(getRide)
    .post(newRide)
router.route('/bookings')
    .get(getBookings)
    .post(addBookings)
router.route('/cancel_ride')
    .post(cancelRide)
router.route('/edit_ride')
    .post(editRide)
router.route('/user')
    .get(getUser)
    .post(saveUser)
router.route('/access')
    .get()
    .post()

router.get('/all-users')
router.get('/all-ev')
router.get('/all-rides',getRides)

module.exports = router