const express = require('express')
const router = express.Router()
const {getRides,editRide,cancelRide,getRide,newRide,getBookings,addBookings, getOngoing} = require('../controllers/rides')
const {getUser,getAllUsers,saveUser} = require('../controllers/user')
const {adminAuth} =  require('../middleware/authorize')
const { getEv,getAllEvs, deleteEv } = require('../controllers/ev')
const {createAdmin} = require('../controllers/admin')

router.use(adminAuth)
router.route('/ev')
    .get(getEv)
    .post()
    .delete(deleteEv)
router.route('/ride')
    .get(getRide)
    .post(newRide)
router.route('/ongoing')
    .get(getOngoing)
router.route('/bookings')
    .get(getBookings)
    .post(addBookings)
router.route('/cancel_ride')
    .post(cancelRide)
router.route('/edit_ride')
    .post(editRide)
router.route('/user')
    .get(getUser)
    .post(saveUser)
router.route('/access')
    .get()
    .post()

router.post('/new-admin',createAdmin)

router.get('/all-users',getAllUsers)
router.get('/all-ev',getAllEvs)
router.get('/all-rides',getRides)

module.exports = router